#!/usr/bin/env bash
ARGS="$@"
BENCHMARK=""
SCHEDULER_CONFIGURATION=""
OTHER_ARGS=""
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
EXT="opt"
PROCS=1

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -p|-proc|--proc)
    PROCS="$2"
    shift
    shift
    ;;
    
    -scheduler_configuration)
    SCHEDULER_CONFIGURATION="$2"
    shift
    shift
    ;;

    -infile)
    INFILE="-infile $SCRIPTPATH/$2"
    shift
    shift
    ;;

    -ext)
    EXT="$2"
    shift
    shift
    ;;

    -benchmark)
    BENCHMARK="$2"
    shift
    shift
    ;;
    
    *)
    OTHER_ARGS="$1 $2 $OTHER_ARGS"
    shift
    shift
    ;;
esac
done

if [ "$BENCHMARK" == "" ]; then
  echo "[ERR] missing benchmark"
  echo $ARGS
  exit 1
fi

if [ "$SCHEDULER_CONFIGURATION" == "cilk" ]; then
   EXT="opt_cilk"
fi

export NUM_THREADS=$PROCS

CPUFREQ=""
case $(hostname -s) in
  tinker*) CPUFREQ="-cpu_frequency_khz 2100000" ;;
  v-test-5038ki*) CPUFREQ="-cpu_frequency_khz 1300000" ;;
  *) ;;
esac

$SCRIPTPATH/$BENCHMARK.$EXT $OTHER_ARGS $INFILE -scheduler_configuration $SCHEDULER_CONFIGURATION -proc $PROCS $CPUFREQ
rc=$?
# the line below is needed because for some reason prun isn't properly
# interpreting crashes, which exit with positive exit codes
if [[ $rc != 0 ]]; then echo "exectime ERROR"; fi 
exit $rc
